samples/Dressca/dressca-backend/src/Dressca.ApplicationCore/Ordering/OrderFactory.cs, samples/Dressca/dressca-backend/src/Dressca.SystemCommon/ObjectExtensions.cs, samples/Dressca/dressca-backend/src/Dressca.Web.Consumer/Controllers/BasketItemsController.cs, samples/Dressca/dressca-backend/tests/Dressca.UnitTests.SystemCommon/ObjectExtensionsTest.cs
- `ObjectExtentions`の名前空間を`System`に変更しました。
- 不要になった`using`を削除しました。
コードのクリーンアップを実行した際に、
マイグレーションファイル`20241211091203_InitialCreate`からも`using`が削除されますが、
マイグレーションファイルにはEFでの自動生成以外で手を加えないほうがよいと判断したため、変更しておりません。
なし
=> ObjectExtentionsの名前空間をSystemに変更

samples/Dressca/dressca-backend/src/Dressca.ApplicationCore/ApplicationService/AssetApplicationService.cs, samples/Dressca/dressca-backend/src/Dressca.EfInfrastructure/Migrations/20241211091203_InitialCreate.cs, samples/Dressca/dressca-backend/src/Dressca.SystemCommon/StringExtentions.cs, samples/Dressca/dressca-backend/tests/Dressca.UnitTests.SystemCommon/StringExtentionsTest.cs
クライアントから引き渡される文字列`assetCode`について、
改行文字を取り除いてからログに出力するよう修正しました。
そのために、`string`  クラスに改行文字を取り除く拡張メソッドを定義しました。
改行文字が含まれる場合、
攻撃者がログに任意の文字列を埋め込むことができるため、
ログを偽装されたり、ログにスクリプトを埋め込まれたりする危険性があります。
なし
https://www.jpcert.or.jp/java-rules/ids03-j.html
=> アセットコードから改行文字を取り除いてからログ出力する

.github/workflows/remove-old-artifacts.yml
アーティファクトの削除にはactions writeのpermissionが必要なため追加する。
なし
- <https://docs.github.com/ja/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-actions>
- <https://docs.github.com/ja/rest/actions/artifacts?apiVersion=2022-11-28#delete-an-artifact>
=> remove-old-artifacts.ymlにactionsのpermissionsを追加

.github/workflows/build-and-release-documents.yml, .github/workflows/check-openapi-generator-update.yml, .github/workflows/remove-old-artifacts.yml, .github/workflows/samples-azure-ad-b2c-auth-ci.yml, .github/workflows/samples-console-app-with-di.ci.yml, .github/workflows/samples-dressca-admin-backend.ci.yml, .github/workflows/samples-dressca-consumer-backend.ci.yml
ワークフローで利用しているサードパーティーのアクションをコミットハッシュを使って指定するように修正しました。
コミットハッシュでアクションのバージョンを固定することで、サプライチェーン攻撃によって意図しないアクションが実行されることを防ぎます。
なし
https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
=> ワークフローのサードパーティーアクションのバージョンをコミットハッシュで固定する

.github/workflows/build-and-release-documents.yml
softprops/action-gh-releaseのバージョンを `v2.2.1` に修正しました。
なし
なし
=> softprops/action-gh-releaseのバージョンを v2.2.1 に更新

.github/workflows/check-openapi-generator-update.yml
- openapi-generatorのアップデート検知フローの対象にAzureADB2CAuthを追加しました。
- 動作確認の上、アップデートが必要な際にIssueが生成・更新されることを確認しました。
- https://github.com/AlesInfiny/maris/issues/2243
なし
なし
=> AzureADB2Cサンプルをopenapi-generatorのアップデート検知ワークフローの対象にする

samples/Dressca/dressca-backend/src/Dressca.ApplicationCore/Authorization/Roles.cs, samples/Dressca/dressca-backend/src/Dressca.Web.Admin/Authorization/Policies.cs, samples/Dressca/dressca-backend/src/Dressca.Web.Admin/Controllers/CatalogItemsController.cs, samples/Dressca/dressca-backend/src/Dressca.Web.Admin/Program.cs, samples/Dressca/dressca-backend/src/Dressca.Web.Admin/dressca-admin-api.json, samples/Dressca/dressca-backend/src/Dressca.Web/Authorization/DummyAuthenticationHandler.cs
- 属性式にはreadonlyの値を渡せない（`[Authorize(Roles = Roles.Admin]`）ので、
- フロントエンド側の下記の変更に備えて、管理者ロールを表す定数の文字列をmaia側に揃えて`ROLE_ADMIN`に変更しました。
- https://github.com/AlesInfiny/maia/pull/1798
なし
なし
=> AdminのControllerのAuthorizeに渡す値が誤っている問題を修正

samples/Dressca/dressca-backend/Directory.Packages.props
`Microsoft.AspNetCore.Mvc.Testing`、`Microsoft.AspNetCore.Mvc.NewtonsoftJson`、`Microsoft.AspNetCore.SpaProxy`、`Microsoft.EntityFrameworkCore`、`Microsoft.EntityFrameworkCore.Design`、`Microsoft.EntityFrameworkCore.SqlServer`、および `Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore` のバージョンを `8.0.11` から `8.0.12` に更新しました。
なし
以下のdependabotのPRは、9.0をターゲットとするものが含まれるため利用しません。
- https://github.com/AlesInfiny/maris/pull/2271
=> Dresscaの依存するNuGetパッケージを更新（8.0.11 > 8.0.12）

samples/AzureADB2CAuth/auth-frontend/app/package.json, samples/Dressca/dressca-frontend/consumer/package.json
- AzureADB2CサンプルとDressacaのconsumerについて、`vite preview`実行時のポートを未指定（デフォルト値）に統一しました。
- 修正対象のワークスペースで`npm run preview`を行い、Viteのサーバーが問題なく立ち上がることを確認しました。
admin はcreate-vueを行ったタイミングの関係で既に未指定になっていたため、対応していません。
maia 側は下記の通り v1.01 にて対応します。
- https://github.com/AlesInfiny/maia/pull/1858
=> AzureADB2Cサンプルとconsumerのpreview時のポートを未指定（デフォルト値）に統一

documents/contents/guidebooks/how-to-develop/dotnet/create-solution-structure.md
- 注意書きの途中にtextlint-enableの設定を記載すると表示が崩れてしまうため、
設定の記載位置を修正いたしました。
なし
- 表示崩れの例を示します。
=> 注意書きのテキストボックスの表示崩れを修正

.github/workflows/check-openapi-generator-update.yml
- issue作成処理の終了ステータスの値が不正な場合は異常終了させるように修正しました。
- 対象のカスタムアクションの終了ステータスの不正を人為的に発生させることが難しいので、実際の挙動は確認できていませんが、この分岐に入った場合は異常終了して欲しいため、リスクは極めて低く問題ないと考えます。
なし
=> issueの作成処理の終了ステータスが不正な場合にワークフローを異常終了させる

samples/Dressca/dressca-backend/tests/Dressca.UnitTests.ApplicationCore/Ordering/OrderFactoryTest.cs
OrderFactoryの単体テストを追加しました。
なし
なし
=> OrderFactoryの単体テストを追加する

.github/workflows/samples-console-app-with-di.ci.yml, samples/ConsoleAppWithDI/solution/Directory.Packages.props, samples/ConsoleAppWithDI/solution/src/Maris.ConsoleApp.Hosting/ConsoleAppHostedService.cs, samples/ConsoleAppWithDI/solution/src/Maris.Logging.Testing/Maris.Logging.Testing.csproj, samples/ConsoleAppWithDI/solution/src/Maris.Logging.Testing/Xunit/TestLoggerManager.cs, samples/ConsoleAppWithDI/solution/src/Maris.Logging.Testing/Xunit/XunitLogger.cs, samples/ConsoleAppWithDI/solution/src/Maris.Logging.Testing/Xunit/XunitLoggerProvider.cs, samples/ConsoleAppWithDI/solution/tests/Directory.Build.props, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/Maris.ConsoleApp.IntegrationTests.csproj, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/ScopeTests/Condition.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/ScopeTests/ObjectState.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/ScopeTests/ScopedTest.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/ScopeTests/SingletonTest.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/ScopeTests/TransientTest.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.IntegrationTests/TestBase.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/Core/AsyncCommandTest.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/Hosting/ConsoleAppContextFactoryTest.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/Hosting/ConsoleAppHostedServiceTest.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/Hosting/ServiceCollectionExtensionsTest.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/Maris.ConsoleApp.UnitTests.csproj, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/TestBase.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/XunitSerializer/CommandBaseXunitSerializer.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/XunitSerializer/ConsoleAppContextXunitSerializer.cs, samples/ConsoleAppWithDI/solution/tests/Maris.ConsoleApp.UnitTests/XunitSerializer/JsonXunitSerializer.cs
テストフレームワークをxUnit v3に移行しました。
カバレッジ取得ツールを `Microsoft.Testing.Extensions.CodeCoverage` に変更しました。
`MemberData` で参照する型に対して、シリアル化ロジックを持つ `IXunitSerializer` を追加しました。
CI時のテストコマンドを修正しました。
PRにテスト結果を表示しないよう修正しました。
なし
- <https://xunit.net/docs/getting-started/v3/custom-serialization>
- <https://github.com/tsuna-can-se/hello-world/pull/71>
- <https://github.com/tsuna-can-se/hello-world/pull/75>
=> ConsoleAppWithDIをxunit-v3へ更新する

.github/workflows/samples-azure-ad-b2c-auth-ci.yml, samples/AzureADB2CAuth/auth-backend/Directory.Packages.props, samples/AzureADB2CAuth/auth-backend/Dressca.sln, samples/AzureADB2CAuth/auth-backend/tests/Directory.Build.props, samples/AzureADB2CAuth/auth-backend/tests/Dressca.IntegrationTest/ApiTest.cs, samples/AzureADB2CAuth/auth-backend/tests/Dressca.IntegrationTest/ApiTestWebApplicationFactory.cs, samples/AzureADB2CAuth/auth-backend/tests/Dressca.IntegrationTest/Dressca.IntegrationTest.csproj
Azure AD B2CサンプルをxUnit v3に移行しました。
コードカバレッジの取得ツールを `coverlet.collector` から `Microsoft.Testing.Extensions.CodeCoverage` に変更しました。
カバレッジ取得ツールの変更にあわせてワークフローを修正しました。
なし
なし
=> Azure AD B2Cサンプルをxunit v3に移行する

samples/ConsoleAppWithDI/solution/Directory.Packages.props
- `Microsoft.Extensions.Logging.Abstractions`を8.0.2から8.0.3に更新しました。
- `Microsoft.NET.Test.Sdk`を17.12.0から17.13.0に更新しました。
- `xunit.runner.visualstudio`を3.0.1から3.0.2に更新しました。
なし
なし
=> ConsoleAppWithDIのNuGetパッケージを更新する

documents/README.md, maris.code-workspace
Fixes #2575
拡張機能のIDを修正しました。
- Change the extension ID in `maris.code-workspace` from `taichi.vscode-textlint` to `3w36zj6.textlint`.
- Update the extension ID in `documents/README.md` from `taichi.vscode-textlint` to `3w36zj6.textlint`.
なし
なし
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/AlesInfiny/maris/pull/2582?shareId=732eaa9b-449e-441b-8403-3144bbbb9eaf).
=> VSCode用のtextlint拡張機能を変更する

samples/AzureADB2CAuth/auth-backend/Directory.Packages.props, samples/AzureADB2CAuth/auth-backend/src/Dressca.Web/dressca-api.json
以下のパッケージのバージョンを更新しました：
- `Microsoft.AspNetCore.Authentication.JwtBearer`, `Microsoft.AspNetCore.Mvc.NewtonsoftJson`, `Microsoft.AspNetCore.Mvc.Testing`, `Microsoft.AspNetCore.SpaProxy`: 8.0.12 から 8.0.14
- `Microsoft.Identity.Web`: 3.5.0 から 3.8.2
- `NSwag.AspNetCore` と `NSwag.MSBuild`: 14.2.0 から 14.3.0
- `xunit.v3`：2.0.0 から 2.0.1
NSwag 系パッケージの更新に伴い、 OpenAPI仕様書を再生成しました。
バージョン番号以外の差異がないことを確認済みです。
なし
なし
=> Azure AD B2CサンプルのNuGetパッケージを更新する

documents/contents/guidebooks/how-to-develop/dotnet/project-settings.md, samples/AzureADB2CAuth/auth-backend/global.json, samples/ConsoleAppWithDI/solution/global.json, samples/Dressca/dressca-backend/global.json
.NET SDK 8系を利用できるよう、 global.json の rollForward : latestMajor に変更しました。
また、プレリリースを許容するかどうかの設定を追加しました。
それに伴い、ドキュメントを修正しました。
textlint の同義語エラーが発生したため、意味が変わらないよう注意しながら修正しました。
なし。
- https://github.com/AlesInfiny/maris/issues/2610
.NET の設定に関する global.json のドキュメント
https://learn.microsoft.com/ja-jp/dotnet/core/tools/global-json
> latestMajor | バージョンが指定された値以上である、インストールされているものの中で最も高い .NET SDK を使用します。見つからない場合は、失敗します。
=> .NET SDK 8系を利用できるよう global.json を修正

samples/Dressca/dressca-backend/Directory.Packages.props
以下のパッケージを最新の.NET 8系に更新しました。
- `Maris.Logging.Testing` 1.0.0 -> 1.1.0
- `Microsoft.EntityFrameworkCore` 8.0.16 -> 8.0.17
- `Microsoft.EntityFrameworkCore.Design` 8.0.16 -> 8.0.17
- `Microsoft.EntityFrameworkCore.SqlServer` 8.0.16 -> 8.0.17
- `Microsoft.NET.Test.Sdk `17.13.0 -> 17.14.1
- `xunit.runner.visualstudio` 3.1.0 -> 3.1.1
- `xunit.v3` 2.0.2 -> 2.0.3
なし
なし
=> DresscaのNuGetパッケージを更新する

documents/hooks/github_markdown_fetcher.py
- 現行のドキュメントには該当箇所がないため、ローカルで下記の拡張子にハイフンを含むファイルのコードスニペットが正しく表示されることを確認しました。
https://github.com/AlesInfiny/maris/blob/main/maris.code-workspace
なし
なし
=> コードスニペットで拡張子にハイフンを含むファイルを表示できない不具合を修正

samples/AzureADB2CAuth/auth-backend/Directory.Packages.props
`Microsoft.AspNetCore.Authentication.JwtBearer`, `Microsoft.AspNetCore.Mvc.NewtonsoftJson`, `Microsoft.AspNetCore.Mvc.Testing`, `Microsoft.AspNetCore.SpaProxy` のバージョンを 8.0.17 から 8.0.18 に更新しました。 `Microsoft.Identity.Web` のバージョンを 3.9.3 から 3.11.0 に更新しました。 `xunit.runner.visualstudio` のバージョンを 3.1.1 から 3.1.3 に、`xunit.v3` のバージョンを 2.0.3 から 3.0.0 に更新しました。
なし
なし
=> Azure AD B2Cサンプルのnugetパッケージ更新

.github/workflows/lint-documents/action.yml, .github/workflows/samples-azure-ad-b2c-auth-ci.yml, .github/workflows/samples-dressca-admin-frontend.ci.yml, .github/workflows/samples-dressca-consumer-frontend.ci.yml
各 CI ワークフローで使用する Node.js のバージョンを LTS バージョンに固定しました。
strategy と matrix の指定により特に複数パターンでの実行を行っていないことを検知したため、不要な設定を削除しました。
ドキュメントのビルドにおいて、Node 18 系を使用していたことに起因する警告が表示されなくなったtことを確認しました。
admin、consumer、azureadb2cサンプルにおいて、ワークフローのログを確認し、
LTS バージョンが使用されていることと、他のアクション中などで不審な警告が出ていないことを確認しました。
```console
Environment details
node: v22.18.0
npm: 10.9.3
yarn: 1.22.22
```
なし
下記のドキュメントに記載の通り、 LTS バージョンを指定するエイリアスが利用できます。
https://github.com/actions/setup-node?tab=readme-ov-file#supported-version-syntax
Maia 側は下記で対応済みです。
- https://github.com/AlesInfiny/maia/pull/2907
=> CI で使用する Node.js のバージョンを LTS バージョンに固定する
